[project]
name = "vf-toxicity-explanation"
version = "0.1.0"
dependencies = [
    "datasets",
    "openai",
    "verifiers",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_toxicity_explanation.py"]
