[project]
name = "vf-truthful-qa"
version = "0.1.0"
description = "TruthfulQA environment for evaluating model truthfulness and informativeness"
dependencies = [
    "verifiers",
    "datasets",
    "openai",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_truthful_qa.py"]