[project]
name = "vf-xml-tool-env"
version = "0.1.0"
dependencies = [
    "verifiers>=0.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_xml_tool_env.py"]
